### ISSUE TITLE
bootstrapping order - make reach-user always first

### ISSUE THREAD

**Issue by mattgi** [reach/api-framework#10]
It is currently impossible to bootstrap data in a module that appears alphabetically before a module that has a table that you depend upon.

For example, attempting to insert Content via the `ui`'s module bootstrap is not possible as it requires a `user_id`. No users exist until the `user` module has loaded and bootstrapped itself.

Not sure how to work around this..

Perhaps `user` is the only special case as it is part of the interface.. as such, `reach-user` could be pushed up the load order and done first.

**Comment by Kodemon** [comment]
This has been resolved, you can now set priority to `true` inside the package.json configuration of a module and it will be loaded in before non prioritised packages.

Right now the one downside is that its not an exact loading priority, so if two packages has to be loaded before the other but both have the priority tag we cannot guarantee load order.

Something to look into for future version.
