### ISSUE TITLE
Errors are swallowed and difficult to debug when they occur

### ISSUE THREAD

**Issue by mattgi** [reach/api-framework#15]
A config was corrupt/invalid but https://github.com/reach/api-framework/blob/master/lib/config.js#L23 did not log anything to the console... so it was like trying to find a needle in a haystack

**Comment by Kodemon** [comment]
Yeah, I am aware of this issue. Haven't had time to look into it but will do that soon. It makes debugging quite difficult since it silently just breaks when something is off.
